[package]
name = "busmust"
description = "Native Rust driver for BUSMUST USB CAN and CAN FD adapters"
authors = ["Dan Glastonbury <dglastonbury@mozilla.com>", "Sergey Anufrienko <serg@anufrienko.net>"]
version = "0.2.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/madprogrammer/busmust-rs"
readme = "../README.md"
documentation = "https://docs.rs/busmust"
keywords = ["busmust", "can", "canfd", "usb"]
categories = ["hardware-support"]

[dependencies]
nusb = "0.2.7"

[lib]
name = "busmust"
path = "src/lib.rs"
